### ISSUE TITLE
Examples page doesn't work

### ISSUE THREAD

**Issue by it-discovery** [zyra/ngx-facebook#100]
Hi

I tried to review examples page https://zyra.github.io/ngx-facebook-example/ but all the buttons don't respond. I also see an error in the console:
Load denied by X-Frame-Options: https://www.facebook.com/xti.php?xt=AZVcjRWTk-obD2yycw2_ndLBUOX3_9xGus1_zklLM0kR0krxChzpiCkIaDP5IxlXTJ56IPJcJ_Id3qUKBDrWPeC3i40wGYZEWOOLPxlAyh8qY3CjkWIvH0zqvhHdhR-Ls5KByTFmPlZEt0WQqoEjb3l4JcbieCZdLCyYQOGxsOB-gQ&isv=1&cts=1505982642&csp does not permit cross-origin framing.

**Comment by danielsogl** [comment]
Reopen the issue if you still have this problem.

**Comment by it-discovery** [comment]
If I open this page now and click 'Login' button new window pops up with an error message: "App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions."
