### ISSUE TITLE
fb-video component does not initialize

### ISSUE THREAD

**Issue by viktorstaikov** [zyra/ngx-facebook#103]
Hi
I'm trying to embed some videos using fb-video component inside [Bootstrap Carousel](https://valor-software.com/ngx-bootstrap/#/carousel). Fb-video is not initializing at all and it has no child elements in the DOM when inspecting the element.

This is how I use it:
`    <fb-video (error)="log($event)" href="https://www.facebook.com/facebook/videos/10153231379946729/"></fb-video>`
The log() function doesn't get called at all.

Could you provide any tips to debug this and see what the issue might be?

**Comment by ihadeed** [comment]
You need to inject the Facebook service in (1) your app's main module, OR (2) on the specific page where you want the components to be visible.
