### ISSUE TITLE
"require function is used in a way in which dependencies cannot be statically extracted" error on build

### ISSUE THREAD

**Issue by bencameron00** [zyra/ngx-facebook#105]
I have an Angular 4.4 application that has been working very well. It uses webpack as part of the build. 

I have just imported ngx-facebook.

I have followed the basic setup instructions how ever I am getting errors when I try to run the app via a 'npm start' command. 

I am getting this message printed many times in the console...

```
WARNING in ./~/ngx-facebook/dist/umd/index.js Critical dependencies: 3:24-31 require function is used in a way in which dependencies cannot be statically extracted  @ ./~/ngx-facebook/dist/umd/index.js 3:24-31
```
--

Any ideas what this might be?

**Comment by ihadeed** [comment]
Are you using the latest version of Webpack?

**Comment by danielsogl** [comment]
Reopen the issue if you still have this problem.
