### ISSUE TITLE
facebook auth popup login

### ISSUE THREAD

**Issue by kodeine** [zyra/ngx-facebook#107]
Browser blocks the facebook auth page as it is a popup while getting permissions. is there a way to not popup and take the user to facebook page with a return uri?

**Comment by kodeine** [comment]
for example, onesignal.com try to login as facebook, it wont do a popup but it would take it to that page so browser dont block first request as a popup blocked.

**Comment by kodeine** [comment]
is this still maintained?

**Comment by DontBeEvilBen** [comment]
Hey @kodeine you close this issue... were you able to find a solution for this? I want the authentication screen to be on the same tab as my page. but i don't see an option to get rid of the popup.
