### ISSUE TITLE
No components are working

### ISSUE THREAD

**Issue by ahsanaasim** [zyra/ngx-facebook#108]
I have added the following url in my index.html
`<script type="text/javascript" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10&appId=1107037259372986"></script>`

tried this one as well
`<script type="text/javascript" src="https://connect.facebook.net/en_US/sdk.js"></script>`

in my component, initialized FacebookService
```
const initParams: InitParams = {
      appId: AppSettingsModule.FB_APP_ID,
      xfbml: true,
      version: 'v2.10'
    };
    fb.init(initParams);
```

and inside of my html file added the following lines
```
<fb-save uri="{{adInfo.url}}" class="pull-left"></fb-save>
<fb-send href="{{adInfo.url}}" class="pull-right"></fb-send>
<fb-like href="https://github.com/zyra/ngx-facebook"></fb-like>
<fb-post href="https://www.facebook.com/20531316728/posts/10154009990506729/"></fb-post>
```

But none of the above is working.

**Comment by ahsanaasim** [comment]
I am using angular 4 with angular cli

**Comment by ilyakrasnov** [comment]
@ahsanaasim see solution here: https://github.com/zyra/ngx-facebook/issues/93. Add the service helped me render posts

**Comment by ihadeed** [comment]
You need to inject the Facebook service in (1) your app's main module, **OR** (2) on the specific page where you want the components to be visible.

**Comment by simeyla** [comment]
Can we please get the documentation updated?
Quickstarts should just work.  People get super frustrated when they don't for something simple. Would be very helpful if the following was clarified.

Currently it says:

> Inject FacebookService and call the init method (optional):
> This method must be called before using login or api methods. It is not required for other methods/components.

However nothing at all works unless I do this. 

Please fix the docs!

In addition do I have to do in this EVERY component. That's AWFUL. The FB API has XFBML.parse() which is meant to parse DOM nodes added later.
