### ISSUE TITLE
Unmet Peer Dependency issues

### ISSUE THREAD

**Issue by b0rgbart3** [zyra/ngx-facebook#110]
During install, I'm having UNMET PEER DEPENDECY issues...
UNMET PEER DEPENDENCY @angular/common@4.4.6
├── UNMET PEER DEPENDENCY @angular/core@4.4.6

I tried runing npm update, uninstalling the cli, cleaning the cache and re-installing the cli -- and I also put 4.4.6 into my package.json for both of these --
`npm install` by itself works fine
but
`npm i --save ngx-facebook`
--generates these two UNMET PEER DEPENDENCY error messages.

**Comment by ihadeed** [comment]
This package doesn't have any peer dependencies. So it cant be causing this.
