### ISSUE TITLE
Async loading sdk script in index.html

### ISSUE THREAD

**Issue by ninlock** [zyra/ngx-facebook#111]
Hi, is there a solution to load sdk async without an error on init? Because if we can't access to facebook like a company the loading of angular App it's equal to a timeout

**Comment by ihadeed** [comment]
Not at the moment, this feature is in mind though and I will be experimenting with it in the next releases. 

Async loading is possible, but it will be done via the ngx-facebook module, not manually (as their docs suggest).

**Comment by murilobd** [comment]
Any news on that?
