### ISSUE TITLE
Subscriebe to Like page event

### ISSUE THREAD

**Issue by odecharette** [zyra/ngx-facebook#112]
Hi

I'm using Angular 4 and I'd like to add a facebook page like button
So I might use <fb-like href="https://github.com/zyra/ngx-facebook"></fb-like>

Is it possible to launch a function in TS when the facebook page is actually liked ?

I'm developping a game and I want to give some extra points to the user if he likes the FB page

Thanks !
Olivia

**Comment by ihadeed** [comment]
Their SDK docs don't mention anything about an event listener on "Like" buttons. (see https://developers.facebook.com/docs/plugins/like-button). Therefore, that functionality is not within the scope of this module. 

You could do it in a hacky way, by checking if the button exists in the DOM and then applying an event listener to it manually. However, this is still not a reliable method to know if the user actually liked the page. If the user is not logged in, the button will open a popup window to prompt for login. Also, the user can click the button again to un-like that page.
