### ISSUE TITLE
How to use fb-video in lazy loaded modules?

### ISSUE THREAD

**Issue by SimranChawla1995** [zyra/ngx-facebook#148]

**Comment by SimranChawla1995** [comment]
I imported FacebookModule in my home module & FacebookService in its providers. Initialized the service in its component but when <fb-video> in html,it's not showing anything.While if i use it normally ,import all of these in app.module . It works fine.I'm not getting where is the problem. Please help.

**Comment by lynx-r** [comment]
+

**Comment by lynx-r** [comment]
This comment helped https://github.com/zyra/ngx-facebook/issues/74#issuecomment-302836161

**Comment by SimranChawla1995** [comment]
I figured the problem was that fb-video was not getting initialized as I did it in constructor. Resolved now.
