### ISSUE TITLE
wrapper not working

### ISSUE THREAD

**Issue by parodenas** [zyra/ngx-facebook#167]
Hello, I have a project where I use "Login" and "fb-post" from this wrapper and yesterday both were working fine, but today all of the sudden they stopped working. Do you have any idea of what happened or if something changed with fb js sdk?

thanks in advanced!

**Comment by e-Neural** [comment]
Hi,

I change:
<script type="text/javascript" src="https://connect.facebook.net/pt_BR/sdk.js"></script>
to
<script type="text/javascript" src="https://connect.facebook.net/pt/sdk.js"></script>

And Work!

**Comment by parodenas** [comment]
thanks @e-Neural for you answer, it was something related with a FB outage affecting JS SDK and JS Social Plugins, but is now solved! thanks 👍
