### ISSUE TITLE
Throw an exception when facebook init fails

### ISSUE THREAD

**Issue by tdesvenain** [zyra/ngx-facebook#67]
Now that exception is catched in init() method, we can't detect if init process failed. This is very annoying.
Could we
- throw an exception if FB.init fails
- or refactor FacebookService.init function into a promise
- or set a state on FacebookService that provides information about fail or success status of init ?
Thanks

**Comment by ihadeed** [comment]
Sure, I like the promise idea. I will implement it when I get a chance. 

Feel free to submit a PR!

**Comment by tdesvenain** [comment]
Thanks !
