### ISSUE TITLE
http://localhost:3000/ngx-facebook 404 (Not Found)

### ISSUE THREAD

**Issue by mohamednagy** [zyra/ngx-facebook#76]
I have followed the steps of how to install the package
`npm i --save ngx-facebook`
then add the facebook sdk to my index.html
`<script type="text/javascript" src="https://connect.facebook.net/en_US/sdk.js"></script>`
from my module
`import { FacebookService, InitParams } from 'ngx-facebook';`
```
constructor(private http: Http, private fb: FacebookService){
		let initParams: InitParams = {
			appId: '1234566778',
			version: 'v2.8'
		};

		fb.init(initParams);
	}
```

but i always stuck on error that `http://localhost:3000/ngx-facebook 404 (Not Found)`

**Comment by bachnxhedspi** [comment]
I found a solution for old version (ng2-facebook-sdk) here #45, but still not able to find solution for ngx-facebook.

**Comment by ihadeed** [comment]
Put the following in your systemjs config file:

```js
  ...
   'ngx-facebook': 'npm:ngx-facebook'
  },
  packages: {
  ...
   'ngx-facebook': {
        defaultExtension: 'js',
        main: 'dist/umd/index.js'
    }
```

**Comment by bachnxhedspi** [comment]
Thanks @ihadeed , you saved my days.

My application run well in development environments; but after build them to production and deploy on server. All I receive is "Uncaught TypeError: Module @angular/core not declared as a dependency."

I use Mgechev's angular 2 seed, which you can find here: https://github.com/mgechev/angular-seed

Please take a look at my source code if you don't mind: https://github.com/bachnxhedspi/gr-angular-client

**Comment by danielsogl** [comment]
Reopen the issue if you still have this problem.
