### ISSUE TITLE
Facebook Graph API no longer returns permissions

### ISSUE THREAD

**Issue by Atkinson88** [zyra/ngx-facebook#78]
I have been using your package for a good month or two now and last night I checked the login with facebook functionality just to confirm it was still working, however it seems to login correctly, but the graph API is called, but email does not get returned? 

This is my code:

`this.fb.init(INIT_PARAMS);` // Which gets set from a constant file - Can confirm it working.

```
this.fb.login().then((rep: any) => {

    console.log(rep);

     this.fb.api(`https://graph.facebook.com/v2.8/${rep.authResponse.userID}?fields=first_name,email&access_token=${rep.authResponse.accessToken}`, 'get').then(person => {
  
debugger;

})
 }).catch((error: any) => {
            this.showModal(UNABLE_TO_LOGIN, GENERAL_ERROR_HEADER);
 });
``` 

Can someone shed any light into why this might not be working anymore?

I've removed the app from my facebook approve apps and logged in again yet the issue is still the same.

**Comment by Atkinson88** [comment]
Resolved.

**Comment by manticarodrigo** [comment]
How?

**Comment by ihadeed** [comment]
@manticarodrigo 

See https://zyra.github.io/ngx-facebook/facebook-service/#login

You need to set `return_scopes` to `true`.

**Comment by manticarodrigo** [comment]
Awesome! Thank you @ihadeed
