### ISSUE TITLE
facebook comments plugin is not display on chrome

### ISSUE THREAD

**Issue by Lagistos** [zyra/ngx-facebook#79]
I added a comments area and it's look ok on the firefox and edge but it's not visible in chrome.
does somebody is familiar with this problem?
is there a way to fix that?

**Comment by xerotolerant** [comment]
I have the same problem except it does not show in chome either.

**Comment by ihadeed** [comment]
Does this help https://github.com/zyra/ngx-facebook/issues/74#issuecomment-302836161?

**Comment by Lagistos** [comment]
Thank you about your answer. but The problem is still exists

**Comment by xerotolerant** [comment]
In my case I needed to initialize the module first. It showed up once I did
that. It wasn't clear what functions required initialization and it failed
silently.

**Comment by Lagistos** [comment]
I did the initialization function again inside the constructor and yet not working on chrome,
all the components working well except the comments component (and it's working well on firefox and edge) even after i updated my chrome it didn't work.

**Comment by ihadeed** [comment]
Ok I'll look into it.

The example project for this repo works fine on Chrome and it shows every single component correctly.

 It's worth checking if you have any browser extensions blocking the comments component.

**Comment by Lagistos** [comment]
i dont have any extention on my chrome, i hope that it's a problem in my browser, thanks a lot.

**Comment by ihadeed** [comment]
Does the example project work fine for you?

**Comment by Lagistos** [comment]
actually no, and i just checked it on other websites with facebbok comments
and it doesnt work there also, so probably the problem is in my browser,
thanks a lot

בתאריך 31 במאי 2017 14:41,‏ "Ibby Hadeed" <notifications@github.com> כתב:

**Comment by amrography** [comment]
It's not showing on opera too. The input `href` is removed when building the project 

This what I write in HTML `<fb-comments [href]="post.link"></fb-comments>`

And this from console
![screen shot 2017-06-20 at 1 07 15 pm](https://user-images.githubusercontent.com/9614340/27330377-6a0d299e-55b9-11e7-836c-5647bec289ab.png)

**Comment by danielsogl** [comment]
Reopen the issue if you still have this problem.
