### ISSUE TITLE
Checking for FB Object existence.

### ISSUE THREAD

**Issue by kyue1005** [zyra/ngx-facebook#80]
The issue is when I am trying to do SSR for my application.
As I am using express to render my application as static html and FB Object wont be initialized, if the facebook service provider can check existence of FB Object before performing FB SDK action would be great.

**Comment by ihadeed** [comment]
I'll improve the module and add more features to make life easier. 

For now, if you're using Angular Universal, see my comment here: https://github.com/zyra/ngx-facebook/issues/72#issuecomment-297558233

**Comment by christofferskog** [comment]
@ihadeed But this happens regardless if you're making any calls. Just by importing the module I get this error and idk how to work around that because I can't wrap the module in an if statement.
