### ISSUE TITLE
Can show comments base on post id ?

### ISSUE THREAD

**Issue by TrungQNguyen** [zyra/ngx-facebook#83]
I have a post id. I want to read all comments (and can post new comment or reply).

Can we do it ?!?!

Thanks

**Comment by ihadeed** [comment]
Is this something that is possible to do with Facebook's JavaScript SDK? if so, please send me the link and I will implement it as soon as I get a chance. If not, then I can't do much about it here. This project is just a wrapper of their JS SDK.

**Comment by TrungQNguyen** [comment]
Ok thanks.
