### ISSUE TITLE
fb.Event.subscribe(...) yields error: Property "Event" does not exist on FacebookService or FacebookModule

### ISSUE THREAD

**Issue by stefems** [zyra/ngx-facebook#84]
Facebook offers this option for keeping track of auth status: https://developers.facebook.com/docs/reference/javascript/FB.Event.subscribe/v2.9

But when I use it in my currently working code (successfully performing init(), login(), checkLoginStatus() and more), .Event.subscribe() is not working. 

```ts
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { Http, Response, Headers, RequestOptions } from '@angular/http';
import { FacebookModule, FacebookService, InitParams } from 'ngx-facebook';
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/delay';
import 'rxjs/add/operator/toPromise';
import { Subject }    from 'rxjs/Subject';


@Injectable()
export class FbloginService {

  constructor (private http: Http, private fb: FacebookService) {
    let initParams: InitParams = {
      appId: '-',
      xfbml: true,
      status: false,
      version: 'v2.9'
    };

    fb.init(initParams);

    fb.Event.subscribe('auth.login', (response) => {
      console.log("subscribed status: " + response.status);
    }); 
  }
}
```

Full Error message: 
Property 'Event' does not exist on type 'FacebookService'.

**Comment by ihadeed** [comment]
This module still has no support for events yet. I'll add it in the next release.

For now, you can do something like this:
```ts
declare var FB: any;

FB.Event.subscribe(...)
```

**Comment by stefems** [comment]
Thanks for the prompt response and helpful advice!

**Comment by anthonyfabrizi** [comment]
@ihadeed How and where to put declare var FB: any; FB.Event.subscribe(...)? It's not working for me.

**Comment by stefems** [comment]
This is a typescript question. Go online to read more about using external JS in typescript files.

You can declare a variable (FB is specifically declared inside the JS you're linking in the index.html file) in your typescript file in order to capture that JS script's global variable. You can do this at the top of the typescript file. console.log() the variable in order to see if it has successfully acquired the global JS variable.

**Comment by usepeachy** [comment]
`import {Injectable} from '@angular/core';
import {Component, OnInit} from '@angular/core';
import {Response, Http} from '@angular/http';
import {Helper} from '../services/helper';
import {Router} from '@angular/router';
import {ToastrService} from '../services/toastr.service';

declare var window: any;
declare var FB: any;

@Injectable()
export class FbloginService implements OnInit {

    constructor(private toastr: ToastrService, private http: Http, private helper: Helper, private router: Router) {

        window.fbAsyncInit = () => {
            FB.init({
                appId: '1919701578316167',
                autoLogAppEvents: false,
                xfbml: false,
                version: 'v2.10'
            });
            FB.AppEvents.logPageView();
        };

        FB.Event.subscribe('auth.statusChange', (response => {
            //this.processWithResponse(response);
            this.toastr.setSuccess(true, 'Done');
        }));

       
    }



    login() {
        FB.login();
    }

    ngOnInit() {
        if (window.FB) {
            window.FB.XFBML.parse();
        }
    }

    processWithResponse(response) {
        FB.Event.unsubscribe('auth.statusChange');
        this.http.post(this.helper.baseUrl('api/social/facebook'),{'token':response.authResponse.accessToken}).subscribe(
        (response) => {
            const data = response.json();
            localStorage.setItem('token', data.token);
            this.router.navigate(['dashboard']);
        },
        (error) => {
            console.log(error.status);

        });
    }

}`
