### ISSUE TITLE
Current User

### ISSUE THREAD

**Issue by YuriFontella** [zyra/ngx-facebook#85]
What is the best way to validate if the user is already logged in? And how can I show user data in the view? When I try this "this.user = response" in getProfile () this.user returns empty.

When I refresh the page and try to access the method getProfile () this error occurs:

Error processing action Object {message: "An active access token should be used to query information about the current user.", Type: "OAuthException", code: 2500, fbtrace_id: "GAgW5NIoeL1"}

**Comment by ihadeed** [comment]
The method [getLoginStatus](https://zyra.github.io/ngx-facebook/facebook-service/#getLoginStatus) is meant for such thing. It checks if there is an active session. If there isn't one, then you need to call `login` again.

**Comment by YuriFontella** [comment]
The getLoginStatus() problem is that it does not return true or false.

**Comment by ihadeed** [comment]
Does the promise returned by the method resolve or reject? What does it resolve/reject with ?

**Comment by YuriFontella** [comment]
It returns the object: {status: "connected", authResponse: Object}
But as for example I would send this to the view to show/hide the login button?

**Comment by ihadeed** [comment]
Yes. You check if the `status` property is equal to `connected`. If it's something else, then you need the user to login again.

**Comment by felipeperezsanchez** [comment]
getLoginStatus always  return unknown
  :-(

**Comment by danielsogl** [comment]
Reopen the issue if you still have this problem.
