### ISSUE TITLE
Login to facebook issue 

### ISSUE THREAD

**Issue by punkkumar113** [zyra/ngx-facebook#87]
I used ngx-facebook I am getting user profile but user profile is not providing me user email what should i do 

Thanks

**Comment by ihadeed** [comment]
Are you requesting the email permission?

**Comment by punkkumar113** [comment]
Yes but I am only getting name and id

**Comment by ihadeed** [comment]
You need to use the `.api()` method to fetch the user's profile.

```ts
this.fb.api('/me').then(...)
```
