### ISSUE TITLE
No components are rendering

### ISSUE THREAD

**Issue by Anglim** [zyra/ngx-facebook#93]
Hi,

After following the simple 3-step guide:
1. Install via NPM
2. Add JavaScript SDK to index.html
3. Import FacebookModule into your app's root module

I get an issue where none of the components I add are displaying.

**For example:**
`<fb-page href="https://facebook.com/facebook"></fb-page>`

Nothing appears on my webpage after adding this.
I have no error in the console.

Anyone have any ideas?

**Comment by EnslavedEagle** [comment]
Same thing is happening to me. I wanted to add a like button to my angular component. The DOM inside the `fb-like` element seems to create just fine (`span` & `iframe`), but no button is present.

**Comment by sarnecki-cic** [comment]
I have the same issue

**Comment by sarnecki-cic** [comment]
OK, so I solved it by calling a service and providing my appId in ts file for this component

**Comment by nkrambo** [comment]
@sarnecki-cic Have you got an example of how you solved this? Thanks

**Comment by tiberiumihai** [comment]
@sarnecki-cic Can you tell us how does it look this call in your ts file?

Currently I have to reload the whole page in order for the iframe to load again by injecting the facebook SDK again.

`var FBSDK = document.getElementById("facebook-jssdk");

    if (FBSDK) {
      FBSDK.remove();
    }

    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));`

But I don't like this solution.

Maybe you have a solution that would work with angular 5 routing?

Thanks!

**Comment by tiberiumihai** [comment]
Looking on ng2-facebook-sdk git repo docs I found how it works.

First you need to create a facebook application, and get your appId.

Then use this:
facebook-panl.ts
```
import { Component, OnInit, AfterViewInit } from '@angular/core';
import { FacebookService, InitParams } from 'ngx-facebook';

@Component({
  selector: 'app-facebook-page-panel',
  templateUrl: './facebook-page-panel.component.html',
  styleUrls: ['./facebook-page-panel.component.scss']
})
export class FacebookPagePanelComponent implements OnInit {
  constructor(private fb: FacebookService) {
    let initParams: InitParams = {
      appId: '1694379800582762',
      xfbml: true,
      version: 'v2.9'
    };
    fb.init(initParams);
  }
}
```

facebook-panel.html
```
  <fb-page data-href="https://www.facebook.com/Your-Facebook-Page"
           data-tabs="timeline"
           data-small-header="true"
           data-width="318"
           data-hide-cover="false"
           data-show-facepile="true">
  </fb-page>
```

**Comment by ihadeed** [comment]
You need to inject the Facebook service in (1) your app's main module, OR (2) on the specific page where you want the components to be visible.
