### ISSUE TITLE
How can I get OAuth facebook code?

### ISSUE THREAD

**Issue by nioperas06** [zyra/ngx-facebook#94]
How can I get OAuth code before ngx-facebook exchanded it for an access token? I want to use [django-rest-social-auth](https://github.com/st4lk/django-rest-social-auth) but I need an input like this: 
`{
      "provider": "facebook",
      "code": "AQBPBBTjbdnehj51"
  }`
Can anyone help me?

**Comment by vortexkd** [comment]
Did you find any solution to this?

**Comment by pelcomppl** [comment]
@vortexkd @nioperas06 Did you find any solution to this?

**Comment by vortexkd** [comment]
@pelcomppl I ended up using the authToken that is returned, and using this to validate it.
https://developers.facebook.com/docs/graph-api/reference/debug_token/
