### ISSUE TITLE
Component not working on Ionic 2

### ISSUE THREAD

**Issue by pablo-gonzalez** [zyra/ngx-facebook#97]
Hi 
I have tried to use your component on my Ionic 2 application with no success.
Also I have tried with a default template for testing and same result.

**Steps to reproduce**
Install Ionic using `npm install ionic@latest`
Create a new project based on a ionic template:
`ionic start sidemenuTest sidemenu`
Complete the first 3 steps of your Installation documentation.

Add fb-page in home.html and list.html between ion-content tags:
```
<ion-content>
  <fb-page href="https://facebook.com/facebook"></fb-page>
</ion-content>

```
Run `ionic serve`

**Issues**
1. fb-page content is shown in home page (root page) only first time. When you change to list page using the menu and then return to home the component is not shown. 
2. fb-page is never shown in the list page (second page).

Thanks in advance,
Pablo

**Comment by danielsogl** [comment]
Reopen the issue if you still have this problem.
