### ISSUE TITLE
Support for pages

### ISSUE THREAD

**Issue by redaxmedia** [zyra/ngx-facebook#98]
Hello,

I try to get the latest events of a facebook page.

```
this.fb.api('/{page-id}/events');
```

Facebook Api returns:

```
An access token is required to request this resource.
```

Of course this does not work without having a token provided but the InitParams does not have such property. So my question is - does this library provide internal handling of access tokens or should I go back to the original SDK?

Thank you

**Comment by ihadeed** [comment]
Did you call `.login()` before trying to use the `.api()` method?

**Comment by redaxmedia** [comment]
Using `.login()` works but I don't want the user to be logged in to display such data. Therefore I like to make an "app-request" in the background. I hope you understand what I try to explain.

**Comment by ihadeed** [comment]
If it needs an access token, then you have to provide it somehow.

`ads_management` or `pages_show_list` permissions are needed for that API endpoint (see https://developers.facebook.com/docs/graph-api/reference/page/events/).

 If you own the page and you insist on getting this data on the client-side of you app... you can generate an access token and send it with the request.

**Comment by redaxmedia** [comment]
Thank you for pointing this out.
